services:
  nextjs:
    image: ghcr.io/thibaud57/thibaud-geisler-portfolio:latest
    pull_policy: always
    restart: unless-stopped
    env_file: .env
    environment:
      ASSETS_PATH: /app/assets
    volumes:
      - portfolio_assets:/app/assets
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "10"

volumes:
  portfolio_assets:
