import type { TagKind } from "@/generated/prisma/client"

export interface TagInput {
  slug: string
  nameFr: string
  nameEn: string
  kind: TagKind
  icon: string | null
  displayOrder: number
}

export const tags: TagInput[] = [
  // === LANGUAGE (4) ===
  {
    slug: "typescript",
    nameFr: "TypeScript",
    nameEn: "TypeScript",
    kind: "LANGUAGE",
    icon: "simple-icons:typescript",
    displayOrder: 1,
  },
  {
    slug: "python",
    nameFr: "Python",
    nameEn: "Python",
    kind: "LANGUAGE",
    icon: "simple-icons:python",
    displayOrder: 2,
  },
  {
    slug: "scala",
    nameFr: "Scala",
    nameEn: "Scala",
    kind: "LANGUAGE",
    icon: "simple-icons:scala",
    displayOrder: 3,
  },
  {
    slug: "java",
    nameFr: "Java",
    nameEn: "Java",
    kind: "LANGUAGE",
    icon: "lucide:coffee",
    displayOrder: 4,
  },

  // === FRAMEWORK (11) ===
  {
    slug: "angular",
    nameFr: "Angular",
    nameEn: "Angular",
    kind: "FRAMEWORK",
    icon: "simple-icons:angular",
    displayOrder: 1,
  },
  {
    slug: "fastapi",
    nameFr: "FastAPI",
    nameEn: "FastAPI",
    kind: "FRAMEWORK",
    icon: "simple-icons:fastapi",
    displayOrder: 2,
  },
  {
    slug: "play",
    nameFr: "Play",
    nameEn: "Play",
    kind: "FRAMEWORK",
    icon: "lucide:chevron-right",
    displayOrder: 3,
  },
  {
    slug: "nodejs",
    nameFr: "Node.js",
    nameEn: "Node.js",
    kind: "FRAMEWORK",
    icon: "simple-icons:nodedotjs",
    displayOrder: 4,
  },
  {
    slug: "express",
    nameFr: "Express",
    nameEn: "Express",
    kind: "FRAMEWORK",
    icon: "simple-icons:express",
    displayOrder: 5,
  },
  {
    slug: "nestjs",
    nameFr: "NestJS",
    nameEn: "NestJS",
    kind: "FRAMEWORK",
    icon: "simple-icons:nestjs",
    displayOrder: 6,
  },
  {
    slug: "react",
    nameFr: "React",
    nameEn: "React",
    kind: "FRAMEWORK",
    icon: "simple-icons:react",
    displayOrder: 7,
  },
  {
    slug: "nextjs",
    nameFr: "Next.js",
    nameEn: "Next.js",
    kind: "FRAMEWORK",
    icon: "simple-icons:nextdotjs",
    displayOrder: 8,
  },
  {
    slug: "spring-boot",
    nameFr: "Spring Boot",
    nameEn: "Spring Boot",
    kind: "FRAMEWORK",
    icon: "simple-icons:springboot",
    displayOrder: 9,
  },
  {
    slug: "android",
    nameFr: "Android",
    nameEn: "Android",
    kind: "FRAMEWORK",
    icon: "simple-icons:android",
    displayOrder: 10,
  },
  {
    slug: "odoo",
    nameFr: "Odoo",
    nameEn: "Odoo",
    kind: "FRAMEWORK",
    icon: "simple-icons:odoo",
    displayOrder: 11,
  },

  // === DATABASE (4) ===
  {
    slug: "mongodb",
    nameFr: "MongoDB",
    nameEn: "MongoDB",
    kind: "DATABASE",
    icon: "simple-icons:mongodb",
    displayOrder: 1,
  },
  {
    slug: "postgresql",
    nameFr: "PostgreSQL",
    nameEn: "PostgreSQL",
    kind: "DATABASE",
    icon: "simple-icons:postgresql",
    displayOrder: 2,
  },
  {
    slug: "qdrant",
    nameFr: "Qdrant",
    nameEn: "Qdrant",
    kind: "DATABASE",
    icon: "lucide:database-zap",
    displayOrder: 3,
  },
  {
    slug: "pgvector",
    nameFr: "pgvector",
    nameEn: "pgvector",
    kind: "DATABASE",
    icon: "simple-icons:postgresql",
    displayOrder: 4,
  },

  // === AI (10) ===
  {
    slug: "google-adk",
    nameFr: "Google ADK",
    nameEn: "Google ADK",
    kind: "AI",
    icon: "simple-icons:google",
    displayOrder: 1,
  },
  {
    slug: "n8n",
    nameFr: "n8n",
    nameEn: "n8n",
    kind: "AI",
    icon: "simple-icons:n8n",
    displayOrder: 2,
  },
  {
    slug: "skills",
    nameFr: "Skills",
    nameEn: "Skills",
    kind: "AI",
    icon: "simple-icons:anthropic",
    displayOrder: 3,
  },
  { slug: "mcp", nameFr: "MCP", nameEn: "MCP", kind: "AI", icon: "lucide:plug", displayOrder: 4 },
  {
    slug: "rag",
    nameFr: "RAG",
    nameEn: "RAG",
    kind: "AI",
    icon: "lucide:database",
    displayOrder: 5,
  },
  {
    slug: "vertex-ai",
    nameFr: "Vertex AI",
    nameEn: "Vertex AI",
    kind: "AI",
    icon: "lucide:sparkles",
    displayOrder: 6,
  },
  {
    slug: "gemini",
    nameFr: "Gemini",
    nameEn: "Gemini",
    kind: "AI",
    icon: "simple-icons:googlegemini",
    displayOrder: 7,
  },
  {
    slug: "anthropic",
    nameFr: "Claude",
    nameEn: "Claude",
    kind: "AI",
    icon: "simple-icons:claude",
    displayOrder: 8,
  },
  {
    slug: "openai",
    nameFr: "ChatGPT",
    nameEn: "ChatGPT",
    kind: "AI",
    icon: "lucide:message-circle",
    displayOrder: 9,
  },
  {
    slug: "perplexity",
    nameFr: "Perplexity",
    nameEn: "Perplexity",
    kind: "AI",
    icon: "simple-icons:perplexity",
    displayOrder: 10,
  },

  // === INFRA (10) ===
  {
    slug: "kafka",
    nameFr: "Kafka",
    nameEn: "Kafka",
    kind: "INFRA",
    icon: "simple-icons:apachekafka",
    displayOrder: 1,
  },
  {
    slug: "docker",
    nameFr: "Docker",
    nameEn: "Docker",
    kind: "INFRA",
    icon: "simple-icons:docker",
    displayOrder: 2,
  },
  {
    slug: "kubernetes",
    nameFr: "Kubernetes",
    nameEn: "Kubernetes",
    kind: "INFRA",
    icon: "simple-icons:kubernetes",
    displayOrder: 3,
  },
  {
    slug: "gcp",
    nameFr: "Google Cloud",
    nameEn: "Google Cloud",
    kind: "INFRA",
    icon: "simple-icons:googlecloud",
    displayOrder: 4,
  },
  {
    slug: "dokploy",
    nameFr: "Dokploy",
    nameEn: "Dokploy",
    kind: "INFRA",
    icon: "lucide:ship",
    displayOrder: 10,
  },
  {
    slug: "github-actions",
    nameFr: "GitHub Actions",
    nameEn: "GitHub Actions",
    kind: "INFRA",
    icon: "simple-icons:githubactions",
    displayOrder: 5,
  },
  {
    slug: "datadog",
    nameFr: "Datadog",
    nameEn: "Datadog",
    kind: "INFRA",
    icon: "simple-icons:datadog",
    displayOrder: 6,
  },
  {
    slug: "elasticsearch",
    nameFr: "Elasticsearch",
    nameEn: "Elasticsearch",
    kind: "INFRA",
    icon: "simple-icons:elasticsearch",
    displayOrder: 7,
  },
  {
    slug: "sentry",
    nameFr: "Sentry",
    nameEn: "Sentry",
    kind: "INFRA",
    icon: "simple-icons:sentry",
    displayOrder: 8,
  },
  {
    slug: "sonarqube",
    nameFr: "SonarQube",
    nameEn: "SonarQube",
    kind: "INFRA",
    icon: "simple-icons:sonarqubeserver",
    displayOrder: 9,
  },

  // === EXPERTISE (8) ===
  {
    slug: "agents-ia",
    nameFr: "Agents IA",
    nameEn: "AI Agents",
    kind: "EXPERTISE",
    icon: "lucide:brain-circuit",
    displayOrder: 1,
  },
  {
    slug: "automatisation",
    nameFr: "Automatisation",
    nameEn: "Automation",
    kind: "EXPERTISE",
    icon: "lucide:workflow",
    displayOrder: 2,
  },
  {
    slug: "developpement-fullstack",
    nameFr: "Développement Full-Stack",
    nameEn: "Full-Stack Development",
    kind: "EXPERTISE",
    icon: "lucide:laptop",
    displayOrder: 3,
  },
  {
    slug: "microservices",
    nameFr: "Microservices",
    nameEn: "Microservices",
    kind: "EXPERTISE",
    icon: "lucide:network",
    displayOrder: 4,
  },
  {
    slug: "programmation-fonctionnelle",
    nameFr: "Programmation fonctionnelle",
    nameEn: "Functional Programming",
    kind: "EXPERTISE",
    icon: "lucide:square-function",
    displayOrder: 5,
  },
  {
    slug: "scraping",
    nameFr: "Scraping",
    nameEn: "Scraping",
    kind: "EXPERTISE",
    icon: "lucide:bug",
    displayOrder: 6,
  },
  {
    slug: "anonymisation",
    nameFr: "Anonymisation",
    nameEn: "Anonymization",
    kind: "EXPERTISE",
    icon: "lucide:ghost",
    displayOrder: 7,
  },
  {
    slug: "anti-bot",
    nameFr: "Anti-bot",
    nameEn: "Anti-bot",
    kind: "EXPERTISE",
    icon: "lucide:shield-ban",
    displayOrder: 8,
  },
]
